# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83cb1e7dc7da90e484d80dbec4428e2381133f4829e54ee682df1df24260adc461e97f29a3c5bc84a95ccf50217d9ebc1d47e7379f918ef9c8f8b5ecf63f0d52

test:
  secret_key_base: 13b4880d055b1698be732a0b8a74b5ae66be63e141e2d99c50310d1904e7b929a33ac22e6e76252e21b995de37dd44d18817bd520b6707d4d8d366bdada97203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
